apiVersion: v1
kind: Service
metadata:
  name: gptnewspaper
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gptnewspaper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
